// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjCqtyozPC604QYQirraVWgtXE65NJE5I',
    appId: '1:551440524442:web:ccd7899cbb3963ea9b2b23',
    messagingSenderId: '551440524442',
    projectId: 'tes1-d6ae0',
    authDomain: 'tes1-d6ae0.firebaseapp.com',
    databaseURL: 'https://tes1-d6ae0-default-rtdb.firebaseio.com',
    storageBucket: 'tes1-d6ae0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLdIQu0OXvv0389bGUsKr2RORy9M2hfs',
    appId: '1:551440524442:android:540d79e0d92eab139b2b23',
    messagingSenderId: '551440524442',
    projectId: 'tes1-d6ae0',
    databaseURL: 'https://tes1-d6ae0-default-rtdb.firebaseio.com',
    storageBucket: 'tes1-d6ae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdExAKRgYbgLfOJXa74vTKjN6G42N1mHk',
    appId: '1:551440524442:ios:474a70e60f993b669b2b23',
    messagingSenderId: '551440524442',
    projectId: 'tes1-d6ae0',
    databaseURL: 'https://tes1-d6ae0-default-rtdb.firebaseio.com',
    storageBucket: 'tes1-d6ae0.firebasestorage.app',
    iosBundleId: 'com.example.tes3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdExAKRgYbgLfOJXa74vTKjN6G42N1mHk',
    appId: '1:551440524442:ios:474a70e60f993b669b2b23',
    messagingSenderId: '551440524442',
    projectId: 'tes1-d6ae0',
    databaseURL: 'https://tes1-d6ae0-default-rtdb.firebaseio.com',
    storageBucket: 'tes1-d6ae0.firebasestorage.app',
    iosBundleId: 'com.example.tes3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjCqtyozPC604QYQirraVWgtXE65NJE5I',
    appId: '1:551440524442:web:5fb31ce0ab876f889b2b23',
    messagingSenderId: '551440524442',
    projectId: 'tes1-d6ae0',
    authDomain: 'tes1-d6ae0.firebaseapp.com',
    databaseURL: 'https://tes1-d6ae0-default-rtdb.firebaseio.com',
    storageBucket: 'tes1-d6ae0.firebasestorage.app',
  );

}